/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StoryRouteImport } from './routes/story'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimelineIndexRouteImport } from './routes/timeline.index'
import { Route as TasksdbIndexRouteImport } from './routes/tasksdb/index'
import { Route as TimelineStepIdRouteImport } from './routes/timeline.$stepId'
import { Route as TasksdbPhaseIdRouteImport } from './routes/tasksdb/$phaseId'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as AdminAdminUpdatesRouteImport } from './routes/admin/_admin/updates'
import { Route as AdminAdminTasksRouteImport } from './routes/admin/_admin/tasks'
import { Route as AdminAdminStepsRouteImport } from './routes/admin/_admin/steps'
import { Route as AdminAdminStatsRouteImport } from './routes/admin/_admin/stats'
import { Route as AdminAdminImagesRouteImport } from './routes/admin/_admin/images'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIndexRoute = TimelineIndexRouteImport.update({
  id: '/timeline/',
  path: '/timeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksdbIndexRoute = TasksdbIndexRouteImport.update({
  id: '/tasksdb/',
  path: '/tasksdb/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineStepIdRoute = TimelineStepIdRouteImport.update({
  id: '/timeline/$stepId',
  path: '/timeline/$stepId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksdbPhaseIdRoute = TasksdbPhaseIdRouteImport.update({
  id: '/tasksdb/$phaseId',
  path: '/tasksdb/$phaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUpdatesRoute = AdminAdminUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTasksRoute = AdminAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStepsRoute = AdminAdminStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStatsRoute = AdminAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminImagesRoute = AdminAdminImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/story': typeof StoryRoute
  '/tasks': typeof TasksRoute
  '/theme': typeof ThemeRoute
  '/updates': typeof UpdatesRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/tasksdb/$phaseId': typeof TasksdbPhaseIdRoute
  '/timeline/$stepId': typeof TimelineStepIdRoute
  '/tasksdb/': typeof TasksdbIndexRoute
  '/timeline/': typeof TimelineIndexRoute
  '/admin/images': typeof AdminAdminImagesRoute
  '/admin/stats': typeof AdminAdminStatsRoute
  '/admin/steps': typeof AdminAdminStepsRoute
  '/admin/tasks': typeof AdminAdminTasksRoute
  '/admin/updates': typeof AdminAdminUpdatesRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/story': typeof StoryRoute
  '/tasks': typeof TasksRoute
  '/theme': typeof ThemeRoute
  '/updates': typeof UpdatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/tasksdb/$phaseId': typeof TasksdbPhaseIdRoute
  '/timeline/$stepId': typeof TimelineStepIdRoute
  '/tasksdb': typeof TasksdbIndexRoute
  '/timeline': typeof TimelineIndexRoute
  '/admin/images': typeof AdminAdminImagesRoute
  '/admin/stats': typeof AdminAdminStatsRoute
  '/admin/steps': typeof AdminAdminStepsRoute
  '/admin/tasks': typeof AdminAdminTasksRoute
  '/admin/updates': typeof AdminAdminUpdatesRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/story': typeof StoryRoute
  '/tasks': typeof TasksRoute
  '/theme': typeof ThemeRoute
  '/updates': typeof UpdatesRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/tasksdb/$phaseId': typeof TasksdbPhaseIdRoute
  '/timeline/$stepId': typeof TimelineStepIdRoute
  '/tasksdb/': typeof TasksdbIndexRoute
  '/timeline/': typeof TimelineIndexRoute
  '/admin/_admin/images': typeof AdminAdminImagesRoute
  '/admin/_admin/stats': typeof AdminAdminStatsRoute
  '/admin/_admin/steps': typeof AdminAdminStepsRoute
  '/admin/_admin/tasks': typeof AdminAdminTasksRoute
  '/admin/_admin/updates': typeof AdminAdminUpdatesRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/story'
    | '/tasks'
    | '/theme'
    | '/updates'
    | '/admin'
    | '/admin/login'
    | '/tasksdb/$phaseId'
    | '/timeline/$stepId'
    | '/tasksdb/'
    | '/timeline/'
    | '/admin/images'
    | '/admin/stats'
    | '/admin/steps'
    | '/admin/tasks'
    | '/admin/updates'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/story'
    | '/tasks'
    | '/theme'
    | '/updates'
    | '/admin/login'
    | '/tasksdb/$phaseId'
    | '/timeline/$stepId'
    | '/tasksdb'
    | '/timeline'
    | '/admin/images'
    | '/admin/stats'
    | '/admin/steps'
    | '/admin/tasks'
    | '/admin/updates'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/story'
    | '/tasks'
    | '/theme'
    | '/updates'
    | '/admin/_admin'
    | '/admin/login'
    | '/tasksdb/$phaseId'
    | '/timeline/$stepId'
    | '/tasksdb/'
    | '/timeline/'
    | '/admin/_admin/images'
    | '/admin/_admin/stats'
    | '/admin/_admin/steps'
    | '/admin/_admin/tasks'
    | '/admin/_admin/updates'
    | '/admin/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StoryRoute: typeof StoryRoute
  TasksRoute: typeof TasksRoute
  ThemeRoute: typeof ThemeRoute
  UpdatesRoute: typeof UpdatesRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  TasksdbPhaseIdRoute: typeof TasksdbPhaseIdRoute
  TimelineStepIdRoute: typeof TimelineStepIdRoute
  TasksdbIndexRoute: typeof TasksdbIndexRoute
  TimelineIndexRoute: typeof TimelineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/': {
      id: '/timeline/'
      path: '/timeline'
      fullPath: '/timeline/'
      preLoaderRoute: typeof TimelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasksdb/': {
      id: '/tasksdb/'
      path: '/tasksdb'
      fullPath: '/tasksdb/'
      preLoaderRoute: typeof TasksdbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/$stepId': {
      id: '/timeline/$stepId'
      path: '/timeline/$stepId'
      fullPath: '/timeline/$stepId'
      preLoaderRoute: typeof TimelineStepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasksdb/$phaseId': {
      id: '/tasksdb/$phaseId'
      path: '/tasksdb/$phaseId'
      fullPath: '/tasksdb/$phaseId'
      preLoaderRoute: typeof TasksdbPhaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/updates': {
      id: '/admin/_admin/updates'
      path: '/updates'
      fullPath: '/admin/updates'
      preLoaderRoute: typeof AdminAdminUpdatesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/tasks': {
      id: '/admin/_admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminAdminTasksRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/steps': {
      id: '/admin/_admin/steps'
      path: '/steps'
      fullPath: '/admin/steps'
      preLoaderRoute: typeof AdminAdminStepsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/stats': {
      id: '/admin/_admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminAdminStatsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/images': {
      id: '/admin/_admin/images'
      path: '/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminAdminImagesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminImagesRoute: typeof AdminAdminImagesRoute
  AdminAdminStatsRoute: typeof AdminAdminStatsRoute
  AdminAdminStepsRoute: typeof AdminAdminStepsRoute
  AdminAdminTasksRoute: typeof AdminAdminTasksRoute
  AdminAdminUpdatesRoute: typeof AdminAdminUpdatesRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminImagesRoute: AdminAdminImagesRoute,
  AdminAdminStatsRoute: AdminAdminStatsRoute,
  AdminAdminStepsRoute: AdminAdminStepsRoute,
  AdminAdminTasksRoute: AdminAdminTasksRoute,
  AdminAdminUpdatesRoute: AdminAdminUpdatesRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StoryRoute: StoryRoute,
  TasksRoute: TasksRoute,
  ThemeRoute: ThemeRoute,
  UpdatesRoute: UpdatesRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  TasksdbPhaseIdRoute: TasksdbPhaseIdRoute,
  TimelineStepIdRoute: TimelineStepIdRoute,
  TasksdbIndexRoute: TasksdbIndexRoute,
  TimelineIndexRoute: TimelineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
